multi_region.configurable_region.*:
  type: config_entity
  label: 'Region config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    weight:
      type: integer
      label: 'Weight'
    status:
      type: boolean
      label: 'Enabled'
    region_languages:
      type: array
      label: 'Region languages'
    default_language:
      type: string
      label: 'Default language'
